WITH LAST_ITEM AS (
    SELECT
        ITEM_ID
    FROM ITEM_TREE
    WHERE ITEM_ID NOT IN (
        SELECT
            PARENT_ITEM_ID
        FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IS NOT NULL
    )
)

SELECT
    I.ITEM_ID,
    I.ITEM_NAME,
    I.RARITY
FROM ITEM_INFO I
JOIN LAST_ITEM L ON I.ITEM_ID = L.ITEM_ID
ORDER BY I.ITEM_ID DESC;