WITH PARENT_COUNT AS (
    SELECT
        PARENT_ID,
        COUNT(*) AS CCOUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)

SELECT
    E.ID,
    IFNULL(P.CCOUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN PARENT_COUNT P ON E.ID = P.PARENT_ID
ORDER BY E.ID ASC;
