WITH SIZE_BY_YEAR AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS DIV_YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY DIV_YEAR
)

SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (S.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID AS ID
FROM ECOLI_DATA E
LEFT JOIN SIZE_BY_YEAR S ON YEAR(E.DIFFERENTIATION_DATE) = S.DIV_YEAR
ORDER BY YEAR, YEAR_DEV ASC;



