WITH MAX_LENGTH AS (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
),
BIG_FISH AS (
    SELECT
        F.ID,
        F.FISH_TYPE,
        F.LENGTH
    FROM FISH_INFO F
    JOIN MAX_LENGTH M ON F.FISH_TYPE = M.FISH_TYPE
        AND F.LENGTH = M.MAX_LENGTH
)

SELECT
    B.ID,
    N.FISH_NAME,
    B.LENGTH
FROM BIG_FISH B
JOIN FISH_NAME_INFO N ON B.FISH_TYPE = N.FISH_TYPE
ORDER BY B.ID ASC;