WITH GRADE_TOTAL AS (
    SELECT
        EMP_NO,
        SUM(SCORE) AS TOTAL
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
),
MAX_TOTAL AS (
    SELECT
        MAX(TOTAL) AS MAX_GRADE
    FROM GRADE_TOTAL
)

SELECT
    G.TOTAL AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES E
JOIN GRADE_TOTAL G ON E.EMP_NO = G.EMP_NO
JOIN MAX_TOTAL M ON G.TOTAL = M.MAX_GRADE;